version: "3.7"

networks:
  traefik-public:
    external: true

services:
  zynomi-api-nodejs:
    container_name: zynomi-api-nodejs
    image: zynomi/zynomi-api-nodejs:latest
    networks:
      - traefik-public
    restart: always
    tty: true
    environment:
      NODE_ENV: production
      DB_URI: "postgres://user:pwd@18.189.3.157:5432/zypress_db"
      DB_SCHEMA: "zypress"
      SAILS_TEMP_FOLDER_PATH: ".temp/"
      SAILS_CODE_GEN_FOLDER_PATH: ".code/"
      WORD_TEMPLATES_FOLDER_PATH: "views/templates/"
    ports:
      - 1337:1337
    #volumes:
    #  - ./zynomi_data:/usr/src/app/views/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zynomi-api-nodejs.tls=true"
      - "traefik.http.routers.zynomi-api-nodejs.rule=Host(`api.zynomi.com`)"
      - "traefik.http.routers.zynomi-api-nodejs.entrypoints=websecure"
      - "traefik.http.routers.zynomi-api-nodejs.tls.certresolver=myresolver"
